---

- hosts: all

  tasks: 
  - name: copy webapp.war to docker host
    template: 
      src: webapp.war
      dest: /home/dockeradmin
    ignore_errors: yes

  - name: copy dockerfile to dockerhost
    template:
      src: Dockerfile
      dest: /home/dockeradmin
    ignore_errors: yes

  - name: build docker image from dockerfile
    shell: docker build -t myapp .
    args:
      chdir: /home/dockeradmin

  - name: deploy tomcat container
    shell: docker run -itd --name tomcat-container -p 8080:8080 myapp
    ignore_errors: yes

  - name: verify container
    shell: docker ps 
    register: output

  - debug:
      msg: echo "{{output}}"


